### ISSUE TITLE
List what grant a given secret has been given?

### ISSUE THREAD

**Issue by kfh** [GoogleCloudPlatform/berglas#135] opened 2020-09-25 08:39 UTC
There doesn't seem to be functionality for doing that now. Should that be a part of the general api ? Or if not, i see this could probably be easily implemented by using functions from for instance (assuming secret manager is used) https://github.com/GoogleCloudPlatform/berglas/blob/main/pkg/berglas/iam_secretmanager.go but most of those are private. Should they be opened up ?

**Comment by sethvargo** [comment] 2020-09-25 13:50
Duplicate of https://github.com/GoogleCloudPlatform/berglas/issues/98#issuecomment-575940477. TL;DR, it's not possible to provide an accurate list.

**Closed by sethvargo** 2020-09-25 13:50 UTC
