### ISSUE TITLE
Support for creating/updating multi-line secrets

### ISSUE THREAD

**Issue by tchupp** [GoogleCloudPlatform/berglas#130] opened 2020-07-30 13:04 UTC
I would expect to be able to create secrets from files with multiple lines. The help text in `berglas create --help` shows:
```
Examples:
  # Create a secret named "api-key" with the contents "abcd1234"
  berglas create my-secrets/api-key abcd1234 \
    --key projects/my-p/locations/global/keyRings/my-kr/cryptoKeys/my-k

  # Read a secret from stdin
  echo ${SECRET} | berglas create my-secrets/api-key - --key...

  # Read a secret from a local file
  berglas create my-secrets/api-key @/path/to/file --key...
```

### Actual behavior
```
$ cat secret.yaml
---
secret:
  data:
    goes:
      there: here!

$ cat secret.yaml | berglas update sm://${GCLOUD_PROJECT}/test-secret -
Successfully updated secret [test-secret] to version [2]

$ berglas access sm://${GCLOUD_PROJECT}/test-secret
---

$ 
```

### Expected behavior
```
$ cat secret.yaml
---
secret:
  data:
    goes:
      there: here!

$ cat secret.yaml | berglas update sm://${GCLOUD_PROJECT}/test-secret -
Successfully updated secret [test-secret] to version [2]

$ berglas access sm://${GCLOUD_PROJECT}/test-secret
---
secret:
  data:
    goes:
      there: here!

$ 
```

I would expect this to match the behavior of `gcloud`

```
$ cat secrets.yaml | gcloud secrets versions add test-secret --data-file=-
Created version [3] of the secret [test-secret].

$ berglas access sm://${GCLOUD_PROJECT}/test-secret
---
secret:
  data:
    goes:
      there: here!

$
```

**Comment by sethvargo** [comment] 2020-07-30 13:06
Duplicate of https://github.com/GoogleCloudPlatform/berglas/issues/115

**Closed by sethvargo** 2020-07-30 13:06 UTC

**Comment by tchupp** [comment] 2020-07-30 14:10
I can see how reading from a file would make this a duplicate issue.
My exact use-case had to do with piping a multi-line output from another command into `berglas update ...`.

I guess one workaround could be to pipe the output to a file, then use the "create from file", then remove that file; but that feels quite awkward, especially when the similar `gcloud` command supports this.
