### ISSUE TITLE
Unable to store multiline passwords into SM

### ISSUE THREAD

**Issue by dennybaa** [GoogleCloudPlatform/berglas#131] opened 2020-08-20 16:01 UTC
Hello, just picks up only the first line

**Comment by sethvargo** [comment] 2020-08-20 16:02
Duplicate of #115

**Closed by sethvargo** 2020-08-20 16:02 UTC

**Comment by dennybaa** [comment] 2020-08-20 16:04
Hmm. I got this. But it's a bug anyways and it's closed) Or you may call it a feature. Nevermind.

**Comment by dennybaa** [comment] 2020-08-20 16:07
And it's annoying! What do you suggest to temporary store secrets on disk)

**Comment by dennybaa** [comment] 2020-08-20 16:10
@sethvargo ?
